### ISSUE TITLE
Cant use your converter,missed .dll

### ISSUE THREAD

**Issue by 505fesc** [Markemp/Cryengine-Converter#129]
It returns: missed hostfxr.dll

**Comment by Markemp** [comment]
That isn't one of the dll's used by the project.  Can you give some more details about your setup?  OS & version, how you are running the exe, etc.  Thanks!

**Comment by Kjasi** [comment]
While not used specifically, it IS a dotNET required DLL.

I recommend reinstalling dotNET.

**Comment by Markemp** [comment]
Closing this issue.  Reinstalling dotnet is probably the right solution.

I'm working on a new version that packages up the framework with the program, but this will significantly increase the size of the app (9MB -> 26MB).  Not really sure that is the direction I want to go though, since any automatically updated Windows 10 computer should have the latest dotnet version installed.
