### ISSUE TITLE
model 

### ISSUE THREAD

**Issue by NomadX688** [Markemp/Cryengine-Converter#130]
Hello, I used your converter to extract a nanosuit model from remastered crysis 3. When converting through a cgf converter, the number of vertices, edges, faces, triangles decreases in the model. Later I exported the model from remastered crysis 2 using noesis the number of vertices, edges, faces, triangles is greater than in remastered crysis 3.Question is it possible to solve the problem of reducing vertices, edges, faces, triangles using cgf
![Снимок экрана 2022-06-21 182514](https://user-images.githubusercontent.com/94874060/174840637-2250595c-88b1-4a92-bf3e-bb01c083e136.png)
![Снимок экрана 2022-06-21 183421](https://user-images.githubusercontent.com/94874060/174840649-4ecfeb33-18db-4490-b6ff-63f453f329c1.png)
?

**Comment by Markemp** [comment]
I think Noesis extracts to .obj files, while cgf-converter defaults to Collada.  Since the number of faces/triangles are almost the same, I think that the vertices aren't reused in the Noesis export.  Cgf-converter can have a single vertex be part of multiple triangles, so I'm guessing that is what is going on here.

Without the source models it's tough to say for sure, but I think this is working properly.  I'm not sure of a use case where having unique vertices per triangle is a desired outcome.

**Comment by Markemp** [comment]
Closing issue.

**Comment by GameOverloads** [comment]
@Markemp For reference, each of these remasters pulls much of the base game work from the ported console editions, so any number of optimizations could have been made to the models when the original console editions were being made to work on the consoles they were slated for, ala Xbox 360 and PS3. So your right in that the models would be different between Crysis 2 Remaster and 3 Remaster , as well with the Crysis 2 model pulled in through Noesis, and the Crysis 3 model pulled in through CGF. So to summarize, their different compared to the original Crysis 2 and 3 models because their based on the original console edition optimized models.
