### ISSUE TITLE
does this not work for .cga?

### ISSUE THREAD

**Issue by eorvedal** [Markemp/Cryengine-Converter#22]
PS D:\depot\miscreated\GameSDK\Objects\vehicles\F100Truck> cgf-converter.exe .\F100Truck.cga -objectdir "d:\depot\miscreated\GameSDK\"
Input file set to .\F100Truck.cga
Data directory set to d:\depot\miscreated\GameSDK\

******************************************************************************
There was an error rendering D:\depot\miscreated\GameSDK\Objects\vehicles\F100Truck\F100Truck.cga

Object reference not set to an instance of an object.

   at CgfConverter.COLLADA.WriteLibrary_Effects() in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 405
   at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 89
   at CgfConverterConsole.Program.Main(String[] args)
******************************************************************************
 

my first time using this, so probably a noob problem.

**Comment by ArtemkaKun** [comment]
Hello, eorvedal
Your question doesn't noob, because of "quite embarrassed" process using this app.
So, how I use this program:
1) Build this program (open cgf-converter.sln with Visual Studio and find an isntruction in Google "how to build solution in VS"). Note - build only in **Release** mod, **not in Debug** or else
2) After build complete (with no errors), go to Cryengine-Converter-github-master\cgf-converter\bin\Release, and you can see cgf-converter.exe
3) In this dir (Cryengine-Converter-github-master\cgf-converter\bin\Release) create a .cmd file with name what you want
4) open this cmd file and paste this
```
cgf-converter *.cgf -objectdir **!!! THERE YOU NEED WRITE PATH WHERE YOU WANT TO SAVE .dae OR .obj FILES !!!**
pause
```
5) So, now you can just put an .cga file near the cgf-converter.exe file 
6) ...
7) PROFIT!1!!

**Comment by Markemp** [comment]
The program does support cga files, as well as .skin and cgf. I don’t have the source files for this game but will see if I can figure out what is going on.

**Comment by Markemp** [comment]
Can you test out this issue with the latest version of the converter?  I don't have the game files, so can't do any significant testing.  Hopefully the latest fixes have helped with these models.

**Comment by Markemp** [comment]
Closing.  Will reopen if it is still an issue.
