### ISSUE TITLE
Unable to convert .obj files

### ISSUE THREAD

**Issue by KeyC0de** [Markemp/Cryengine-Converter#25]
Single conversion doesn't work:
cgf-converter palm_tree_large_a_con.cgf -obj -noconflict

Bulk conversion doesn't work:
cgf-converter.exe *.cgf -obj D:\mydir\ 

My target files were cgf files from CryEngine 5's GameSDK.

**Comment by Markemp** [comment]
Exporting to obj is no longer supported. Please try to export to Collada (dae). If it gives you an error from the command line, please post it here. 

To bulk convert, you need to run it as a loop, not pass a directory as an argument.  The tutorial videos can show you how to do that with some simple Powershell commands. Let me know if you need some help with this part as well, since command prompts can be challenging to people not used to them.

**Comment by KeyC0de** [comment]
I did convert to Collada and then back to my target format through 3ds Max plugins. I'm just reporting that .obj doesn't work, since on the readme you provide instructions for .obj conversion. Thanks.

**Comment by Markemp** [comment]
Ah, got it. I’ll leave this issue open as a task to update the documentation. Thanks for the info!

**Comment by Markemp** [comment]
Updated the Readme file.
